version: "3.7"

services:
  wordpress:
    image: wordpress:5.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$MYSQL_DB_HOST:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
        
  webserver:
    depends_on:
      - wordpress      
    build:
      context: ./lamp
      dockerfile: Dockerfile
    image: vovataras/crash_course:lamp
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - wordpress:/var/www/html
    networks:
      - app-network
        
volumes:
  wordpress:

networks:
  app-network:
    driver: bridge
